DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  created_at TIME DEFAULT CURRENT_TIME,
  order_status VARCHAR(255) DEFAULT 'Pending',
  user_id int REFERENCES users (id) ON DELETE CASCADE
);
